package Royal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;

@XmlAccessorType(XmlAccessType.FIELD)
public class OD_PREMIUM { 
	private String BASIC_PREMIUM_AND_NON_ELECTRICAL_ACCESSORIES;
	private String ELECTRICAL_ACCESSORIES;
	private String BI_FUEL_KIT;
	private String FIBER_GLASS_TANK;
	private String AUTOMOBILE_ASSOCIATION_DISCOUNT;
	private String VOLUNTARY_DEDUCTABLES;
	private String VOLUNTARY_DEDUCTABLE;
	private String NO_CLAIM_BONUS;
	private String DEPRECIATION_WAIVER;
	private String ENGINE_PROTECTOR;
	private String NCB_PROTECTOR;
	private String WIND_SHIELD_GLASS;
	private String LIFE_TIME_ROAD_TAX;
	private String SPARE_CAR;
	private String INVOICE_PRICE_INSURANCE;
	private String LOSS_OF_BAGGAGE;
	private String TOTAL_OD_PREMIUM;
	private String KEY_REPLACEMENT;
	private String TOWING_CHARGES_COVER_PREMIUM;
	private String TYRE_COVER;
	
	
	public String getBASIC_PREMIUM_AND_NON_ELECTRICAL_ACCESSORIES() {
		return BASIC_PREMIUM_AND_NON_ELECTRICAL_ACCESSORIES;
	}
	      
	public void setBASIC_PREMIUM_AND_NON_ELECTRICAL_ACCESSORIES(String bASIC_PREMIUM_AND_NON_ELECTRICAL_ACCESSORIES) {
		BASIC_PREMIUM_AND_NON_ELECTRICAL_ACCESSORIES = bASIC_PREMIUM_AND_NON_ELECTRICAL_ACCESSORIES;
	}
	public String getELECTRICAL_ACCESSORIES() {
		return ELECTRICAL_ACCESSORIES;
	}
	      
	public void setELECTRICAL_ACCESSORIES(String eLECTRICAL_ACCESSORIES) {
		ELECTRICAL_ACCESSORIES = eLECTRICAL_ACCESSORIES;
	}
	public String getBI_FUEL_KIT() {
		return BI_FUEL_KIT;
	}
	      
	public void setBI_FUEL_KIT(String bI_FUEL_KIT) {
		BI_FUEL_KIT = bI_FUEL_KIT;
	}
	public String getFIBER_GLASS_TANK() {
		return FIBER_GLASS_TANK;
	}
	      
	public void setFIBER_GLASS_TANK(String fIBER_GLASS_TANK) {
		FIBER_GLASS_TANK = fIBER_GLASS_TANK;
	}
	public String getAUTOMOBILE_ASSOCIATION_DISCOUNT() {
		return AUTOMOBILE_ASSOCIATION_DISCOUNT;
	}
	      
	public void setAUTOMOBILE_ASSOCIATION_DISCOUNT(String aUTOMOBILE_ASSOCIATION_DISCOUNT) {
		AUTOMOBILE_ASSOCIATION_DISCOUNT = aUTOMOBILE_ASSOCIATION_DISCOUNT;
	}
	public String getVOLUNTARY_DEDUCTABLES() {
		return VOLUNTARY_DEDUCTABLES;
	}
	      
	public void setVOLUNTARY_DEDUCTABLES(String vOLUNTARY_DEDUCTABLES) {
		VOLUNTARY_DEDUCTABLES = vOLUNTARY_DEDUCTABLES;
	}
	public String getVOLUNTARY_DEDUCTABLE() {
		return VOLUNTARY_DEDUCTABLE;
	}
	      
	public void setVOLUNTARY_DEDUCTABLE(String vOLUNTARY_DEDUCTABLE) {
		VOLUNTARY_DEDUCTABLE = vOLUNTARY_DEDUCTABLE;
	}
	public String getNO_CLAIM_BONUS() {
		return NO_CLAIM_BONUS;
	}
	      
	public void setNO_CLAIM_BONUS(String nO_CLAIM_BONUS) {
		NO_CLAIM_BONUS = nO_CLAIM_BONUS;
	}
	public String getDEPRECIATION_WAIVER() {
		return DEPRECIATION_WAIVER;
	}
	      
	public void setDEPRECIATION_WAIVER(String dEPRECIATION_WAIVER) {
		DEPRECIATION_WAIVER = dEPRECIATION_WAIVER;
	}
	public String getENGINE_PROTECTOR() {
		return ENGINE_PROTECTOR;
	}
	      
	public void setENGINE_PROTECTOR(String eNGINE_PROTECTOR) {
		ENGINE_PROTECTOR = eNGINE_PROTECTOR;
	}
	public String getNCB_PROTECTOR() {
		return NCB_PROTECTOR;
	}
	      
	public void setNCB_PROTECTOR(String nCB_PROTECTOR) {
		NCB_PROTECTOR = nCB_PROTECTOR;
	}
	public String getWIND_SHIELD_GLASS() {
		return WIND_SHIELD_GLASS;
	}
	      
	public void setWIND_SHIELD_GLASS(String wIND_SHIELD_GLASS) {
		WIND_SHIELD_GLASS = wIND_SHIELD_GLASS;
	}
	public String getLIFE_TIME_ROAD_TAX() {
		return LIFE_TIME_ROAD_TAX;
	}
	      
	public void setLIFE_TIME_ROAD_TAX(String lIFE_TIME_ROAD_TAX) {
		LIFE_TIME_ROAD_TAX = lIFE_TIME_ROAD_TAX;
	}
	public String getSPARE_CAR() {
		return SPARE_CAR;
	}
	      
	public void setSPARE_CAR(String sPARE_CAR) {
		SPARE_CAR = sPARE_CAR;
	}
	public String getINVOICE_PRICE_INSURANCE() {
		return INVOICE_PRICE_INSURANCE;
	}
	      
	public void setINVOICE_PRICE_INSURANCE(String iNVOICE_PRICE_INSURANCE) {
		INVOICE_PRICE_INSURANCE = iNVOICE_PRICE_INSURANCE;
	}
	public String getLOSS_OF_BAGGAGE() {
		return LOSS_OF_BAGGAGE;
	}
	      
	public void setLOSS_OF_BAGGAGE(String lOSS_OF_BAGGAGE) {
		LOSS_OF_BAGGAGE = lOSS_OF_BAGGAGE;
	}
	public String getTOTAL_OD_PREMIUM() {
		return TOTAL_OD_PREMIUM;
	}
	      
	public void setTOTAL_OD_PREMIUM(String tOTAL_OD_PREMIUM) {
		TOTAL_OD_PREMIUM = tOTAL_OD_PREMIUM;
	}
	public String getKEY_REPLACEMENT() {
		return KEY_REPLACEMENT;
	}
	      
	public void setKEY_REPLACEMENT(String kEY_REPLACEMENT) {
		KEY_REPLACEMENT = kEY_REPLACEMENT;
	}
	public String getTOWING_CHARGES_COVER_PREMIUM() {
		return TOWING_CHARGES_COVER_PREMIUM;
	}
	      
	public void setTOWING_CHARGES_COVER_PREMIUM(String tOWING_CHARGES_COVER_PREMIUM) {
		TOWING_CHARGES_COVER_PREMIUM = tOWING_CHARGES_COVER_PREMIUM;
	}
	public String getTYRE_COVER() {
		return TYRE_COVER;
	}
	      
	public void setTYRE_COVER(String tYRE_COVER) {
		TYRE_COVER = tYRE_COVER;
	}
	
	@Override
	public String toString() {
		return "OD_PREMIUM [BASIC_PREMIUM_AND_NON_ELECTRICAL_ACCESSORIES="
				+ BASIC_PREMIUM_AND_NON_ELECTRICAL_ACCESSORIES + ", ELECTRICAL_ACCESSORIES=" + ELECTRICAL_ACCESSORIES
				+ ", BI_FUEL_KIT=" + BI_FUEL_KIT + ", FIBER_GLASS_TANK=" + FIBER_GLASS_TANK
				+ ", AUTOMOBILE_ASSOCIATION_DISCOUNT=" + AUTOMOBILE_ASSOCIATION_DISCOUNT + ", VOLUNTARY_DEDUCTABLES="
				+ VOLUNTARY_DEDUCTABLES + ", VOLUNTARY_DEDUCTABLE=" + VOLUNTARY_DEDUCTABLE + ", NO_CLAIM_BONUS="
				+ NO_CLAIM_BONUS + ", DEPRECIATION_WAIVER=" + DEPRECIATION_WAIVER + ", ENGINE_PROTECTOR="
				+ ENGINE_PROTECTOR + ", NCB_PROTECTOR=" + NCB_PROTECTOR + ", WIND_SHIELD_GLASS=" + WIND_SHIELD_GLASS
				+ ", LIFE_TIME_ROAD_TAX=" + LIFE_TIME_ROAD_TAX + ", SPARE_CAR=" + SPARE_CAR
				+ ", INVOICE_PRICE_INSURANCE=" + INVOICE_PRICE_INSURANCE + ", LOSS_OF_BAGGAGE=" + LOSS_OF_BAGGAGE
				+ ", TOTAL_OD_PREMIUM=" + TOTAL_OD_PREMIUM + ", KEY_REPLACEMENT=" + KEY_REPLACEMENT
				+ ", TOWING_CHARGES_COVER_PREMIUM=" + TOWING_CHARGES_COVER_PREMIUM + ", TYRE_COVER=" + TYRE_COVER + "]";
	}

}
